---
- name: Создание сети
  community.docker.docker_network:
    name: app_network
    driver: overlay

- name: Выкладка сервиса
  include: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
