---
- name: Installation Docker
  block:
    - name: Adding universe
      apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Установка дополнительных пакетов
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: true
        cache_valid_time: 86400

    - name: Adding Docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Installing stable repo
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Install Docker-ce
      apt:
        name: docker-ce
        update-cache: true

    - name: Check Docker installed and rebooted
      service:
        name: docker
        state: restarted
        enabled: true
  become: true

- name: Install Docker-compose
  block:
    - name: Get latest version Docker-compose
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: page

    - name: Install Docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
  become: true

- name: Install additional packages python
  block:
    - name: install pip packages
      pip:
        name: docker

- name: Finishing the install
  block:
    - name: Adding user to Dockers group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: reboot
      reboot:
  become: true
